# -*- coding: utf-8 -*-
"""MINPRO 1 PRAKTIUKUM AVD Dharma Pala Candra (2409116065)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugWXlqlialojU747dNmwUgWXeO7iv36l

DATASET

tgl: Tanggal Kejadian

ot: Waktu kejadian

lat: Garis lintang, dari 6S sampai 11N

lon: Garis Bujur, dari 142E sampai 94E

depth: kedalaman gempa (km)

mag: magnitudo gempa dari 1 sampai 9.5

remark: daerah kejadian

terkadang, mekanisme fokus peristiwa diukur. Dalam hal ini, nilai dip1, strike1, rake1, dip2, strike2, dan rake2 tidak boleh kosong.
"""

import pandas as pd

data = "/content/katalog_gempa.csv"

read = pd.read_csv(data)

read

"""STUDI KASUS:


*   Menghitung rata-rata magnitudo gempa bumi di Indonesia.

*   Menghitung daerah yang sering terjadi gempa.

*   Menghitung hubungan magnitudo dan kedalaman.

*   Membuat visualisasi sederhana untuk mempresentasikan hasil analisis.

**BUSINEES UNDERSTANDING**

TUJUAN Diambilnya studi kasus tersebut diantar lain:


*   Mengetahui rata rata magnitudo gempa bumi yang ada di indonesia.

*   Mengetahui daerah yang sering terjadi gempa.

*   Mengetahui hubungan magnitudo dan kedalaman.

*   Mengetahui bagaimana jika data di atas di jadikan sebuah data visualisasi untuk di analisa

Apakah data di atas mempunyai masalah?


*   Tidak ada, untuk menjawab studi kasus di atas data tersebut sudah baik untuk menjawabnya. karena tidak ada masalah, maka lanjut ke bagian analisa dan visualisasi.

ANALISA DATASET

Menghitung rata-rata magnitudo:
"""

read.agg({'mag': ['mean']})

"""Menghitung daerah yang sering terjadi gempa:"""

read.value_counts("remark")

"""VISUALISASI DATA

"Visualisasi data di atas mengambil 20000 baris pertama dari data set"

alias dari 1 november 2008 sampai 23 maret 2015

Korelasi Magnitudo dengan kedalamannya.
"""

from matplotlib import pyplot as plt
_df_7.plot(kind='scatter', x='depth', y='mag', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

"""korelasi banyaknya gempa dengan koordinat di indonesia"""

from matplotlib import pyplot as plt
read.plot(kind='scatter', x='lat', y='lon', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

"""Gambaran kasar untuk visualisai di atas:

gambar berbentuk seperti  kepala hiu dengan tanduknya.

*   untuk tanduknya itu daerah maluku dan sekitarnya.

*   untuk mata dan bagian atasnya itu merupakan bagian sulawesi.

*   untuk rahang itu merupakan bagian dari pulau jawa.

*   dan bagian paling bawah itu merupakan bagian dari pulau sumatera.

**KESIMPULAN**

Dari dataset di atas terdapat beberapa poin yang ingin saya sampaikan, yaitu:


*   Berdasarkan data di atas, rata-rata magnitudo adalah sebesar 3.5 yang merupakan gempa dengan kerusakan ringan.

*   Daerah yang paling banyak terkena gempa yaitu provinsi sulawesi, lebih tepatnya daerah utara sulawesi atau semenanjung minahasa.

*   Pada visualisasi data dari korelasi magnitudo dan depth, terdapat sebuah pola yaitu: semakin kecil kedalamannya maka semakin beragam juga magnitudonya.

*   Pada visualisasi data korelasi banyaknya gempa dengan koordinat di indonesia,
terdapat keunikan, yaitu: terdapat celah kosong pada bagian tengah dan membentuk visualisasi data seperti kepala hiu. celah yang kosong tersebut ialah koordinat dari pulau kalimantan yang artinya kalimantan jarang terkena gempa bumi.
"""